# Generated by Django 4.2.6 on 2023-10-31 01:58

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physique', models.IntegerField()),
                ('intellect', models.IntegerField()),
                ('skill', models.IntegerField()),
                ('perception', models.IntegerField()),
                ('empathy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=api.models.generate_slug, editable=False, max_length=4, unique=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=255)),
                ('secret_occupation', models.CharField(blank=True, max_length=255)),
                ('faction', models.CharField(max_length=255)),
                ('biography', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('portrait', models.ImageField(upload_to='portraits/')),
                ('appearance_description', models.TextField(blank=True)),
                ('background_secret', models.TextField()),
                ('stats', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.stat')),
            ],
        ),
    ]
