# Generated by Django 4.2.6 on 2023-10-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_character_nick_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='portrait',
        ),
        migrations.AddField(
            model_name='character',
            name='portrait_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
