version: '3.9'


services:
  db:
    image: mysql:8.0
    container_name: ryf-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DDBB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
    volumes:
      - ./mysql_data:/var/lib/mysql


  backend:
    build: .
    container_name: backend
    command: gunicorn config.wsgi:application -c /usr/src/config/gunicorn.config.py
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - db


  nginx:
    image: nginx:1.25
    container_name: ryf-nginx
    restart: always
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      # - ./certbot/www:/var/www/certbot/:ro
      # - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - backend

