# Generated by Django 4.2.6 on 2023-11-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_character_portrait_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='portrait_filename',
        ),
        migrations.AddField(
            model_name='character',
            name='portrait_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
