# Generated by Django 4.2.6 on 2023-11-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_character_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='appearance_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
